### ISSUE TITLE
Form composition.

### ISSUE THREAD

**Issue by stellarhoof** [smartprocure/mobx-autoform#18]
Say you've got a couple forms `form1` and `form2` like the example in the readme:
```
let form = Form({
  fields: {
    email: {
      label: 'Email Address',
      rules: 'required|email'
    },
    password: {
      rules: 'required',
    },
  },
  submit: async snapshot => {
    await serviceCall(snapshot)
  },
  validate: validatorJS(V),
})
```

There's currently no way of composing them. Such composition should:
- Return the same data structure as the form itself enriched with extra context, so the form would have to be "lifted" in monadic terms.
- On submitting the entire form, carry over results from earlier forms, effectively making the composition a monad. This allows us to compose `submit`s generically, since we can have a subform that depends on results from previous subforms.

Those are the harder ones. The semantics of composing `reset`, `validate`, etc... are trivial. We just iterate through the composed forms and call those methods in order.

**Comment by daedalus28** [comment]
Just summarizing our off-github conversation: I'm not sure I see the value in this because it's trivial to compose fields (just use object spread) and even submit methods are just functions that you can compose. The net savings would likely only be a few lines of code at the cost of introducing new concepts and API surface for form composition instead of just regular functional/object composition.

With that said, we definitely should at least create a canonical _example_ of doing this, even if there's no official API (like how focusing a field has a demo but now underlying actual API is needed in this library).
